# Generated by Django 4.2.4 on 2023-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=200)),
                ('is_type', models.CharField(choices=[('cafe', 'cafe'), ('coworking space', 'coworking space'), ('open area', 'open area'), ('hostel', 'hostel')], max_length=25)),
                ('has_internet', models.BooleanField(default=False)),
                ('is_meeting_friendly', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('location', models.ManyToManyField(to='spaces.location')),
            ],
        ),
    ]
